apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller
  name: controller
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller
  name: webhook-receiver
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http-webhook
  type: ClusterIP
